### ISSUE TITLE
Failed to load resource: net::ERR_CONNECTION_REFUSED alpha61.com/ethereum.json

### ISSUE THREAD

**Issue by rlavolee** [badmofo/ethereum-mining-calculator#15]
Hi,

You're app doesn't seem to work anymore due to loading failure of the `ethereum.json` file.

Regards,
Rémi

**Comment by badmofo** [comment]
I don't see any such error when I try https://badmofo.github.io/ethereum-mining-calculator/   

Are you sure the problem isn't something local?

**Comment by badmofo** [comment]
Nevermind.  You're right ... problem has to do with firewall rules on the machine the ethereum.json file lives.  Fixing now.

**Comment by rlavolee** [comment]
Thanks
