### ISSUE TITLE
wrong info being fetched

### ISSUE THREAD

**Issue by mathieujobin** [badmofo/ethereum-mining-calculator#19]
the ETH price being fetched from coinmarketcap from your live version is 685.625
which is quite outdated... i wonder what else is outdated.

does it need a refresh ?

I wanted to evaluate how long it would take to pay back a GTX 1070 by mining ETH

thank you

**Comment by badmofo** [comment]
Sorry the refresh script broke when the data source it used changed the format.  I've just fixed it.
