### ISSUE TITLE
1e6 1e9

### ISSUE THREAD

**Issue by bmatthewshea** [badmofo/ethereum-mining-calculator#20]
Question - not an issue:
Why are these hex numbers (1e6 and 1e9) used?
thanks

**Comment by badmofo** [comment]
These numbers are not hex but are [exponential notation](https://en.wikipedia.org/wiki/Scientific_notation#E-notation).  1e6 = 1000000   1e9 = 1000000000

**Comment by bmatthewshea** [comment]
Yeah. Took me 5 more mins yesterday and realized it was exp... -> thanks for quick reply, though!
